name: test_appdistribution
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.test_appdistribution
    iosBundleIdentifier: com.example.testAppdistribution
