name: Build & upload to Firebase App Distribution

on:
  pull_request:
    types:
      - opened
      - closed
  branches:
    - main

jobs:
  build:
    if: (github.event.action == 'opened' && github.event_name == 'pull_request')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - name: Increase version code and change version name
        run: |
          # Update build.gradle with new version code and name
          echo "${{ env.VERSION_CODE }} .... ${{ env.version_name }} .... ${{ env.CURRENT_VERSION }}"
      