name: Build & upload to Firebase App Distribution

on:
  push:
    branches:
      - main
    pull-request:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      