name: Build & upload to Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact
        with:
          name: release-apk
          path: build/host/outputs/apk/release/app-release.apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APP_ID}}
            token: ${{secrets.TOKEN}}
            groups: pre-test
            file: build/host/outputs/apk/release/app-release.apk
